export const FETCH_PRODUCTS_BEGIN = "FETCH_PRODUCTS_BEGIN";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";

export const FETCH_PRODUCT_BEGIN = "FETCH_PRODUCT_BEGIN";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ITEM_QUANTITY = "CHANGE_CART_ITEM_QUANTITY";
export const CART_AMOUNT = "CART_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const APPLY_FILTER = "APPLY_FILTERS";
export const APPLY_SORT = "APPLY_SORT";
