export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const FETCH_PRODUCT = "FETCH_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ITEM_QUANTITY = "CHANGE_CART_ITEM_QUANTITY";
export const CART_AMOUNT = "CART_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";

export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const APPLY_FILTER = "APPLY_FILTERS";
export const APPLY_SORT = "APPLY_SORT";
export const APPLY_MAX_PRICE = "APPLY_MAX_PRICE";
